version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./web/:/usr/src/app/
    env_file: .env
    environment:
      DEBUG: 'true'
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    # command: /usr/local/bin/gunicorn web.wsgi:application -w 2 -b :8000

  server:
    restart: always
    build: ./server
    links:
      - postgres:postgres
    # volumes:
    #   - ./web/:/usr/src/app/
    env_file: .env
    command: python server.py
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'postgres'

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  web-static: