version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn web.wsgi:application -w 2 -b :8000

  server:
    restart: always
    build: ./server
    links:
      - postgres:postgres
    # volumes:
    #   - ./web/:/usr/src/app/
    env_file: .env
    command: python server.py

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata: